# Generated by Django 6.0.3 on 2026-04-04 06:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Livro'), (2, 'Autor')])),
                ('id_alvo', models.PositiveIntegerField()),
                ('nota', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('conteudo', models.TextField(blank=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('visibilidade', models.BooleanField(default=True)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_publicacao'],
                'unique_together': {('usuario', 'tipo', 'id_alvo')},
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Livro'), (2, 'Autor'), (3, 'Comentário')])),
                ('id_alvo', models.PositiveIntegerField()),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='social.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('data_voto', models.DateTimeField(auto_now_add=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='social.avaliacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto em Avaliação',
                'verbose_name_plural': 'Votos em Avaliações',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'avaliacao'), name='unique_vote')],
            },
        ),
        migrations.CreateModel(
            name='ComentarioLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_like', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like em Comentário',
                'verbose_name_plural': 'Likes em Comentários',
                'unique_together': {('usuario', 'comentario')},
            },
        ),
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_seguindo', models.DateTimeField(auto_now_add=True)),
                ('seguindo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_seguindo', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguidor',
                'verbose_name_plural': 'Seguidores',
                'unique_together': {('usuario', 'seguindo')},
            },
        ),
        migrations.CreateModel(
            name='SeguidorAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_seguindo', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores_usuarios', to='livro.autor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores_seguindo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguidor de Autor',
                'verbose_name_plural': 'Seguidores de Autores',
                'unique_together': {('usuario', 'autor')},
            },
        ),
        migrations.CreateModel(
            name='StatusLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('lendo', 'Lendo'), ('lido', 'Lido'), ('abandonado', 'Abandonado')], default='nao_iniciado', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('numero_paginas_lidas', models.PositiveIntegerField(default=0)),
                ('favorito', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='livro.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status de Leitura',
                'verbose_name_plural': 'Status de Leituras',
                'unique_together': {('usuario', 'livro')},
            },
        ),
    ]
